import type { Metadata } from "next";
import { kanit } from "@/libs/font";
import Navbar from "@/components/Navbar";
import AntdStyledComponentsRegistry from "@/components/AntdStyledComponentsRegistry";
import "./globals.css";
import Footer from "@/components/Footer";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className + ' flex flex-col pt-4'}>
        <div className="flex">
          <Navbar />
        </div>
        <div className="flex flex-col items-center mt-6">
          <Suspense fallback={<div>Loading...</div>}>
            <AntdStyledComponentsRegistry>
              {children}
            </AntdStyledComponentsRegistry>
          </Suspense>
        </div>
        <Footer />
      </body>
    </html>
  );
}
